version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /usr/bin/supervisord -c /src/supervisord.conf
    environment:
      - PORT=3000
    ports:
      - 3000:3000
